    version: '3.4'

    networks:
      dev:
        driver: bridge

    services:
      mvc:
        image: ${DOCKER_REGISTRY-}mvc
        depends_on:
          - "db"
        build:
          context: .
          dockerfile: MVC/Dockerfile
        networks: 
          - dev
          
      db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'mvc'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - "3306:3306"
        volumes:
          - mysql_data:/var/lib/mysql
        networks:
          - dev
    volumes:
      mysql_data:

